config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  resources :users, only: [:show]
  root to: 'offers#index'

  get '/offers', to: 'offers#index', as: :offers # in link to helper say offers_path
  get '/offers/new', to: 'offers#new', as: :new_offer
  get '/offers/:id', to: 'offers#show', as: :offer
  post '/offers/:offer_id/bookings', to: 'bookings#create', as: :offer_bookings
  delete '/bookings/:id', to: 'bookings#destroy', as: :booking
  post '/offers', to: 'offers#create'
  get '/offers/:id', to: 'offers#edit', as: :update_offer
  patch '/offers/:id', to: 'offers#update'
  # USER Controller
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show'
  # DASHBOARD Controller
  get '/users/:user_id/dashboard', to: 'dashboards#show', as: :dashboard

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/models/offer_review.rb
class OfferReview < ApplicationRecord
  has_many :offers
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings # bookings as a client
  has_many :offers
  has_many :bookings_as_owner, through: :offers, source: :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def create
        @booking = Booking.new(booking_params)
        @offer = Offer.find(params[:offer_id])
        @booking.offer = @offer
        @booking.user = current_user
        if @booking.save
            redirect_to offer_path(@offer), alert: "Yeah, you booked a Friend."
        else
            render "offers/show"
        end
    end

    private

    def booking_params
        params.require(:booking).permit(:start_date, :end_date)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_user, :check

  def show
    @user = User.find_by_id(params[:user_id])
    @bookings = Booking.where(user_id: @user.id)
  end

  private

  def set_user
    @user = User.find_by_id(params[:user_id])
  end

  def check
    return redirect_to root_path, notice: "Sorry, you can only access your own profile silly." unless current_user == @user
  end
end

app/controllers/offer_review_controller.rb
class OfferReviewController < ApplicationController

    def new
        @review = OfferReview.new
    end

    def show
        @review = OfferReview.find_by_id(params[:id])
        @offer = Offer.new
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @offers = Offer.all

    @users = User.all

    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: { offer: offer }),
        image_url: helpers.asset_url("peepoop.png")
      }
    end
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id
    @offer.save
    redirect_to offers_path(@offer)
  end

  def show
    @offer = Offer.find_by_id(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Your Friend-Search-Offer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @offer.destroy
    redirect_to offer_url, notice: 'Your Friend-Search-Offer was successfully destroyed.'
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :photo, :location, :price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<%= @check %>
<div class="dashboard">
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <p class="h4">Hi, <%= @user.firstname.downcase.capitalize() %> here are your bookings</p>
      </div>
    </div>



    <div class="row">
          <div class="card-my-orders">
            <% @bookings.each do |element| %>
            <div class="col-33">
              <p class="my-bookings-title"><strong><%= element.offer.title  %></strong></p>
              <p><%= element.offer.description  %></p>
              <p>Map: <%= element.offer.location  %></p>
              <p>Price: <%= element.offer.price  %> €</p>
              <p>Event Starts: <%= element.start_date.strftime("%A, %b %d")  %></p>
              <p>Event Ends: <%= element.end_date.strftime("%A, %b %d")  %></p>
              <p>Event created on: <%= element.offer.created_at.strftime("%A, %b %d")  %></p>
           </div>
                <!-- TODO: map should show location of -->
            <div class="map-of-order">
             <div style="width: 100%; height: 350px; border-radius: 5px;"
                data-controller="mapbox"
                data-mapbox-markers-value="<%= @markers.to_json %>"
                data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
             <% end %>
          </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetAFriendSeriously</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "layouts/components/device" %>
    <%= render "layouts/components/navbar" %>

    <div class="pages">
      <%= yield %>
    </div>
    <%= render "layouts/components/footer" %>

  </body>
</html>

app/views/layouts/components/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.25),rgba(0,0,0,0.3)), url(<%= asset_path 'banner-img.jpg' %>);">
  <div class="container-banner">
    <h1>Hey pal you should <strong>get a friend, seriously!</strong></h1>
    <p>And if you have friends but need money offer yourself!</p>
      <%= link_to "Offer yourself", new_offer_path, class: "book-now" %>
    </div>
  </div>
</div>

app/views/layouts/components/_device.html.erb
# Devise
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/components/_footer.html.erb
 <div class="footer">
  <div class="footer-links">
  <a href="#"><i class="fab fa-instagram"></i></a>
  <a href="#"><i class="fab fa-facebook"></i></a>
  <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    get a friend, seriously!
  </div>
</div>

app/views/layouts/components/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to "/offers", class: "navbar-brand" do %>
          <%= image_tag "logo.png" %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <% if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "Home", "/offers", class: "nav-link" %>
              </li>
              <li class="nav-item">
              </li>
              <li class="nav-item dropdown">
                <% if current_user.photo.attached? && !current_user.nil? %>
                  <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else  %>
                  <%= image_tag "https://res.cloudinary.com/get-a-friend-seriously/image/upload/v1645708667/avatar_ho49au.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>


                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Dashboard", dashboard_path(current_user), class: "dropdown-item" %>
                  <%= link_to "New Offer", new_offer_path, class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

app/views/offer_review/new.html.erb
<div>
  <h1>create a Review</h1>

  <%= simple_form_for(@review) do |f| %>
    <%= f.input :description, as: :text %>
    <%= f.input :stars, collection: 1..5 %>
    <div class="form-actions middle">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/offer_review/show.html.erb
<h1>Review</h1>

<%= @review.description %>
<% if @review.stars == 1 %>
    <p>*</p>
<% elsif @review.stars == 2 %>
    <p>**</p>
<% elsif @review.stars == 3 %>
    <p>***</p>
<% elsif @review.stars == 4 %>
    <p>****</p>
<% elsif @review.stars == 5 %>
    <p>*****</p>
<% end %>

app/views/offers/_info_window.html.erb
<h2><%= offer.title %></h2>
<p><%= offer.description %></p>
<p><%= offer.location %></p>

app/views/offers/index.html.erb
<%= render "layouts/components/banner" %>
<div class="offer_grid1">

    <% @offers[0..0].each do |element| %>
                <div class="card-trip picture1">
                <% if element.user.photo.attached? %>
                <%= cl_image_tag(element.user.photo.key, gravity: :face, class: "card-image", alt: "image") %>
                <% end %>
                  <div class="card-trip-infos">
                    <div>
                      <div class="price">
                        <h2><%= link_to element.title.truncate(20), "/offers/#{element.id}" %></h2>
                        <h2 class="card-trip-pricing"><%= element.price %> €</h2>
                      </div>
                      <p><%= element.description.truncate(200)%> </p>
                    </div>
                  <hr>
                  </div>
                  <div class="location-highlight">
                    <i class="far fa-compass "></i> <%= element.location %></li>
                  </div>
                </div>
    <% end %>
      <% @offers[1..1].each do |element| %>
                <%= cl_image_tag(element.photo.key) if element.photo.key %>
                <div class="card-trip picture2">
                <% if element.user.photo.attached? %>
                <%= cl_image_tag(element.user.photo.key, gravity: :face, class: "card-image", alt: "image") %>
                <% end %>
                  <div class="card-trip-infos">
                    <div>
                      <div class="price">
                        <h2><%= link_to element.title.truncate(20), "/offers/#{element.id}" %></h2>
                        <h2 class="card-trip-pricing"><%= element.price %> €</h2>
                      </div>
                      <p><%= element.description.truncate(200) %> </p>
                    </div>
                  <hr>
                  </div>
                  <div class="location-highlight">
                    <i class="far fa-compass "></i> <%= element.location %></li>
                  </div>
                </div>
    <% end %>
      <% @offers[2..2].each do |element| %>
                <%= cl_image_tag(element.photo.key) if element.photo.key %>
                <div class="card-trip picture3">
                <% if element.user.photo.attached? %>
                <%= cl_image_tag(element.user.photo.key, gravity: :face, class: "card-image", alt: "image") %>
                <% end %>
                  <div class="card-trip-infos">
                    <div>
                      <div class="price">
                        <h2><%= link_to element.title.truncate(20), "/offers/#{element.id}" %></h2>
                        <h2 class="card-trip-pricing"><%= element.price %> €</h2>
                      </div>
                      <p><%= element.description.truncate(200) %> </p>
                    </div>
                  <hr>
                  </div>
                  <div class="location-highlight">
                    <i class="far fa-compass "></i> <%= element.location %></li>
                  </div>
                </div>
    <% end %>
      <% @offers[3..3].each do |element| %>
                <%= cl_image_tag(element.photo.key) if element.photo.key %>
                <div class="card-trip picture4">
                <% if element.user.photo.attached? %>
                <%= cl_image_tag(element.user.photo.key, gravity: :face, class: "card-image", alt: "image") %>
                <% end %>
                  <div class="card-trip-infos">
                    <div>
                      <div class="price">
                        <h2><%= link_to element.title.truncate(20), "/offers/#{element.id}" %></h2>
                        <h2 class="card-trip-pricing"><%= element.price %> €</h2>
                      </div>
                      <p><%= element.description.truncate(200) %> </p>
                    </div>

                  <hr>
                  </div>
                  <div class="location-highlight">
                    <i class="far fa-compass "></i> <%= element.location %></li>
                  </div>
                </div>
    <% end %>


</div>

<div class="with-map ">
  <div class="left">
    <%# <div class="offer_grid"> %>
      <% @offers[4..15].each do |element| %>
        <%= link_to  "/offers/#{element.id}" do  %>
      <div class="container">
        <div class="inner-container">
          <ul>
              <div class="card_title">

                <li class="title"><%=element.title.truncate(6)%></li>

                <% if element.user.photo.attached? %>
                <%= cl_image_tag(element.user.photo.key, width: 60, height: 60, crop: :thumb, gravity: :face, class: "avatar-regular", alt: "avatar") %>
                <% end %>
              </div>
              <div class="description"><%= element.description.truncate(60)%></div>
              <hr>
              <div class="card_info">
                <li><i class="far fa-compass"></i> <%= element.location %></li>
              </div>
              <!--
              <li class="start"><%= element.start_time %></li>
              <li class="end"><%= element.end_time %></li>
              <li>Uder ID: <%= element.user_id %></li>
              <li>Created: <%= element.created_at %></li>
              <li>Updated: <%= element.updated_at %></li>
              -->
          </ul>
        </div>

      </div>
        <% end %>
      <% end %>
  </div>
  <div class="right">
        <div style="width: 450px; height: 750px; border-radius: 5px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
  </div>
</div>


</div>

app/views/offers/new.html.erb
<div class="login">
  <h1>create an offer</h1>

  <%= simple_form_for(@offer) do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :location %>
    <div class="price-input"><%= f.input :price, placeholder: '0,00 €'%></div>
    <div class="form-actions middle">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/offers/show.html.erb
<div class="login">
  <h1><%= @offer.title %>'s offer</h1>

    <p>Location: <%= @offer.title %></p>
  <div class="offers-body">
    <p>Price : <%= @offer.price %> €</p>
    <p>Created at: <%= @offer.created_at %></p>
    <div class="description">
      <%= @offer.description %>
    </div>
  </div>


  <%= simple_form_for [@offer, @booking] do |f| %>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
  <div class="form-actions middle">
    <%= f.button :submit %>
  </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/index.html.erb
<h1>BlaBla</h1>
<p>Find me in app/views/users/index.html.erb</p>

<div class="user_card">
  <container>
    <h2>Blablabla</h2>
    <ul class='list-unstyled'>
    <% @users.each do |user| %>
      <div class='mt-3'>
      <%= cl_image_tag(user.photo.key) if user.photo.attached? %>
      <li><strong>First name: </strong><%= user.firstname %></li>
      <li><strong>Last name: </strong><%= user.lastname %></li>
      <li><%= user.description %></li>
      <li><strong>Email: </strong><%= user.email %></li>
      <li><strong>Interests: </strong><%= user.interests %></li>
      <li><strong>Location: </strong><%= user.location %></li>
      </div>
      ------------------------------------------
    <% end %>
    </ul>
  </container>
</div>

app/views/users/show.html.erb
<h1><%= @user.firstname %></h1>
<%= cl_image_tag(@user.photo.key) if @user.photo.attached? %>
<div>
  <container>
    <ul>
      <li><strong>First name: </strong><%= @user.firstname %></li>
      <li><strong>Last name: </strong><%= @user.lastname %></li>
      <li><%= @user.description %></li>
      <li><strong>Email: </strong><%= @user.email %></li>
      <li><strong>Interests: </strong><%= @user.interests %></li>
      <li><strong>Location: </strong><%= @user.location %></li>
    </ul>
  </container>
</div>